// <auto-generated />
using System;
using CodeFirst.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirst.Migrations
{
    [DbContext(typeof(CodeFirstContext))]
    [Migration("20231016093441_OnModelCreating")]
    partial class OnModelCreating
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeFirst.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("Note")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Car");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 30,
                            ExamDate = new DateTime(2023, 10, 16, 10, 34, 41, 448, DateTimeKind.Local).AddTicks(9999),
                            Name = "Pepe",
                            Note = 10m
                        },
                        new
                        {
                            Id = 2,
                            Age = 35,
                            ExamDate = new DateTime(2023, 10, 16, 10, 34, 41, 449, DateTimeKind.Local).AddTicks(42),
                            Name = "Luis",
                            Note = 7m
                        },
                        new
                        {
                            Id = 3,
                            Age = 29,
                            ExamDate = new DateTime(2023, 10, 16, 10, 34, 41, 449, DateTimeKind.Local).AddTicks(45),
                            Name = "Ana",
                            Note = 8.4m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
